server:
  port: 8082

spring:
  datasource:
    myshop-authz:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/myshop_authz?serverTimezone=Asia/Seoul
      username: root
      password: 11111111

    myshop-key:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/myshop_key?serverTimezone=Asia/Seoul
      username: root
      password: 11111111

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show_sql: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
