server:
  port: 8082

#spring:
#  redis:
#    host: localhost
#    port: 6379
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      authentication-database: admin
#      database:
#      username:
#      password:
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#    show_sql: false
#
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
